### ISSUE TITLE
기존 eAMEMu 업데이트

### ISSUE THREAD

**Issue by ghostdeleted** [juchan1220/eAMEMu_RN#1]
기존 eAMEMu 앱을 사용하다 기존 앱을 지우고 RN 버전을 설치했는데, 기존 버전의 SID 를 RN버전으로 옮겨올수는 없을까요?

**Comment by juchan1220** [comment]
React Native로 만든 버전은 의도적으로 SID를 사용자 임의로 설정할 수 없도록 만들었습니다. 기존 버전의 SID를 유지해야 하는 특별한 사유가 있나요?

**Comment by ghostdeleted** [comment]
특별한 사유는 없습니다, 기존의 카드에서 새 카드로 데이터를 이전해야겠네요, 답변 감사합니다
