### ISSUE TITLE
[English Version] Deactivate/Activate text is flipped

### ISSUE THREAD

**Issue by cawfeechino** [juchan1220/eAMEMu_RN#10]
Tap to deactivate is currently the disabled state while tap to activate is the enabled state, when it should be the other way around, where tap to deactivate is the enabled state and tap to activate is the disabled state.

**Comment by juchan1220** [comment]
Thank you for reporting the issue! There was a mistake while adding i18n support.

The issue will be fixed in the upcoming version. I am going to release it around tomorrow.

**Comment by juchan1220** [comment]
I just released a new version 3.1.1, which includes the fix for this issue. Sorry for the late release!
